version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      # 🔹 Identifiants Twilio (backend /api/phone/send-code & /verify-code)
      TWILIO_ACCOUNT_SID: "SK0df31b795d885c8a93fc9daa1356c65b"
      TWILIO_AUTH_TOKEN: "GMblu5VP6Pcub87jfYgbfZJkuxXLszrm"
      TWILIO_VERIFY_SERVICE_SID: "VAe1918edb66615c56354bc83751dbda7"

  caddy:
    image: caddy:2
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./reverse-proxy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
